---
apiVersion: v1
kind: Secret
metadata:
  name: hcloud
  namespace: kube-system
stringData:
  token: "${hcloud_token}"
  network: "${network_id}"
  location: "nbg1"
  lb_enabled: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: hcloud-csi
  namespace: kube-system
stringData:
  token: "${hcloud_token}"